// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP1udZDdkS4KfZnGFkl6d4Wo1FG7iNtho',
    appId: '1:569897212889:web:9a33524cc48b2d2d1a97c8',
    messagingSenderId: '569897212889',
    projectId: 'first-app-lelkov',
    authDomain: 'first-app-lelkov.firebaseapp.com',
    storageBucket: 'first-app-lelkov.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp602eA4mpRTJxQuYbGejx7dssmW0QTFs',
    appId: '1:569897212889:android:8b8459645685fbd11a97c8',
    messagingSenderId: '569897212889',
    projectId: 'first-app-lelkov',
    storageBucket: 'first-app-lelkov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNPIpGK05u6LUQMr4hvkvAQAOsHaeaFP4',
    appId: '1:569897212889:ios:3cb88fc36c9fa6521a97c8',
    messagingSenderId: '569897212889',
    projectId: 'first-app-lelkov',
    storageBucket: 'first-app-lelkov.appspot.com',
    iosBundleId: 'com.example.firstAppLelkov',
  );
}
